wzh/blog/models.py
from mongoengine import *
import datetime

connect(db='test', alias='test')


class Post(Document):
    title = StringField()
    subtitle = StringField()
    meta = StringField()
    postdate = DateTimeField(default=datetime.datetime.now)
    tags = ListField(StringField())
    url = StringField()
    fileid = StringField()

    meta = {'db_alias': 'test'}

wzh/blog/__init__.py
from flask import Blueprint
from flask_mongoengine import MongoEngine

blog = Blueprint(
    'blog',
    __name__,
    template_folder='templates',
    static_folder='static'
)

from . import views

wzh/blog/views.py
import markdown
from flask import request, render_template, redirect, url_for, Markup
from . import blog
import requests
from .models import Post


@blog.route('/')
def home():
    return redirect(url_for('.index'))

@blog.route('/index')
def index():
	posts = [post for post in Post.objects]
	content = {'objects':posts}
	return render_template('index.html', **locals())


@blog.route("/post/<pid>")
def post(pid):
    post = Post.objects(id=pid).first()
    page = download_file_from_google_drive(post.fileid)
    page = Markup(markdown.markdown(page))
    return render_template('post.html', **locals())


@blog.route('/about')
def about():
	return render_template('about.html')



@blog.route('/contact')
def contact():
	return render_template('contact.html')



def download_file_from_google_drive(id):
    URL = "https://docs.google.com/uc?export=download"

    session = requests.Session()

    response = session.get(URL, params = { 'id' : id }, stream = True)
    token = get_confirm_token(response)

    if token:
        params = { 'id' : id, 'confirm' : token }
        response = session.get(URL, params = params, stream = True)

    return save_response_content(response)    

def get_confirm_token(response):
    for key, value in response.cookies.items():
        if key.startswith('download_warning'):
            return value

    return None

def save_response_content(response):
    CHUNK_SIZE = 32768    
    return ''.join([chunk.decode('utf-8') for chunk in response.iter_content(CHUNK_SIZE)])

wzh/blog/templates/about.html
{% extends "base.html" %}



{% block content %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url( {{ url_for('blog.static', filename='img/about-bg.jpg') }} )">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>About Me</h1>
              <span class="subheading">帅呆啦</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p></p>
          <p>帅呆啦</p>
        </div>
      </div>
    </div>

    <hr>


{% endblock %}

wzh/blog/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Blog</title>
        <!-- Bootstrap core CSS -->
        <link href="{{ url_for('blog.static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
        <link href="{{ url_for('blog.static', filename='css/clean-blog.min.css') }}" rel="stylesheet">

        <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>

        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    {% endblock %}
</head>


    {% block navbar %}
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <a class="navbar-brand" href="{{ url_for('blog.index') }}"></a>
            <button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
                <i class="fa fa-bars"></i>
            </button>
            <div class="navbar-collapse collapse" id="navbarResponsive" style="">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blog.index') }}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blog.about') }}">About</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('blog.contact') }}">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    {% endblock %}


<body>
    {% block content %}
    {% endblock %}
</body>

<footer>
    {% block footer %}
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2017</p>
                </div>
            </div>
        </div>
    {% endblock %}
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{{ url_for('blog.static', filename='vendor/jquery/jquery.min.js') }}"></script>
<script src="{{ url_for('blog.static', filename='vendor/popper/popper.min.js') }}"></script>
<script src="{{ url_for('blog.static', filename='vendor/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('blog.static', filename='js/clean-blog.min.js') }}"></script>




</html>

wzh/blog/templates/contact.html
{% extends "base.html" %}



{% block content %}
    <!-- Page Header -->
    <header class="masthead" style="background-image: url( {{ url_for('blog.static', filename='img/contact-bg.jpg') }} )">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="page-heading">
              <h1>Contact Me</h1>
              <hr class="small">
              <span class="subheading">Have questions? I have answers (maybe).</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
          <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
          <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
          <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
          <form name="sentMessage" id="contactForm" novalidate>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Name</label>
                <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Email Address</label>
                <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group col-xs-12 floating-label-form-group controls">
                <label>Phone Number</label>
                <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <div class="control-group">
              <div class="form-group floating-label-form-group controls">
                <label>Message</label>
                <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                <p class="help-block text-danger"></p>
              </div>
            </div>
            <br>
            <div id="success"></div>
            <div class="form-group">
              <button type="submit" class="btn btn-secondary">Send</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <hr>

{% endblock %}

wzh/blog/templates/index.html
{% extends "base.html" %}



{% block content %}
<!-- Page Header -->

    <header class="masthead" style="background-image: url(  {{ url_for('blog.static', filename='img/home-bg.jpg') }} )">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h1>THIS IS TRIVIAL</h1>
              <span class="subheading"></span>
            </div>
          </div>
        </div>
      </div>
    </header>


    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">

        {% for p in content.objects %}
          <div class="post-preview">
            <a href="{{ url_for('blog.post', pid=p.id)}}">
              <h2 class="post-title">
                {{p.title}}
              </h2>
              <h3 class="post-subtitle">
                {{p.subtitle}}
              </h3>
              <p class="post-meta">Posted by
              <a href="#">Start Bootstrap</a>
              on September 24, 2017</p>
          </div>
          <hr>
          {% endfor %}

          <!-- Pager -->
          <div class="clearfix">
            <a class="btn btn-secondary float-right" href="#">Older Posts &rarr;</a>
          </div>
        </div>
      </div>
    </div>

    <hr>

{% endblock %}

wzh/blog/templates/post.html
{% extends "base.html" %}


{% block content %}

    <!-- Page Header -->
    <header class="masthead" style="background-image: url( {{ url_for('blog.static', filename='img/post-bg.jpg') }} ) ">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="post-heading">
              <h1> {{ post.title }} </h1>
              <h2 class="subheading"> {{ post.subtitle }} </h2>
              <span class="meta">Posted by
                <a href="#">Start Bootstrap</a>
                on August 24, 2017</span>
            </div>
          </div>
        </div>
      </div>
    </header>

    <!-- Post Content -->
    <article>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">

            {{ page }}
          
          </div>
        </div>
      </div>
    </article>

    <hr>

{% endblock %}